config/routes.rb
Rails.application.routes.draw do
  root "produtos#index"

  get "produtos/search", to: "produtos#search"
  resources :produtos, only: %i[index new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true
  validates :preco, numericality: { greater_than: 0 }
  validates :quantidade,
            numericality: {
              only_integer: true,
              greater_than_or_equal_to: 0
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produtos = Produto.order(nome: :desc)
    @produtos_com_desconto = Produto.order(:preco).limit(1)
  end

  def new
    @produto = Produto.new
  end

  def create
    produto_params =
      params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
    @produto = Produto.new(produto_params)
    if @produto.save
      flash[:notice] = "Produto #{@produto.nome} criado com sucesso!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    Produto.destroy(params[:id])
    redirect_to root_path
  end

  def search
    @produtos = Produto.where("nome LIKE ?", "%#{params[:nome]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Loja", brand_link: root_path do %>
      <%= menu_group do %>
        <%= menu_item "Criar novo produto", new_produto_path %>
      <% end %>
      <%= form_with url: produtos_search_path, method: :get,
          class: "navbar-form navbar-right" do |form| %>
        <div class="form-group">
          <%= form.text_field :nome, class: "form-control", placeholder: "Nome" %>
        </div>
        <%= form.submit "Buscar", class: "btn btn-default" %>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/produtos/index.html.erb
<h1>Produtos</h1>
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="1"></td>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td><%= button_to "Remover", produto_path(produto.id),
                    method: :delete,
                    data: { confirm: "Tem certeza que deseja remover o produto #{produto.nome}?" },
                    class:"btn btn-danger" %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<div class="alert alert-success" role="alert">
    <h2 class="alert-heading">Produtos com desconto</h2>
</div>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
        <% @produtos_com_desconto.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>
<%= form_with model: @produto do |form| %>
    <div class="row">
        <div class="form-group col-sm-8">
            <%= form.label :nome, "Nome" %>
            <%= form.text_field :nome, class: "form-control" %>
            <% @produto.errors.full_messages_for(:nome).each do |message| %>
                <small class="text-danger"><%= "#{message}." %></small>
            <% end %>
        </div>
        <div class="form-group col-sm-8">
            <%= form.label :descricao, "Descrição" %>
            <%= form.text_area :descricao, class: "form-control" %>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-sm-2">
            <%= form.label :preco, "Preço" %>
            <%= form.number_field :preco, class: "form-control", step: 0.01 %>
            <% @produto.errors.full_messages_for(:preco).each do |message| %>
                <small class="text-danger"><%= "#{message}." %></small>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-sm-2">
            <%= form.label :quantidade, "Quantidade" %>
            <%= form.number_field :quantidade, class: "form-control" %>
            <% @produto.errors.full_messages_for(:quantidade).each do |message| %>
                <small class="text-danger"><%= "#{message}." %></small>
            <% end %>
        </div>
    </div>
    <%= form.submit "Criar", class: "btn btn-primary" %>
<% end %>

app/views/produtos/search.html.erb
<h1>Produtos</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
            <td colspan="1"></td>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td><%= button_to "Remover", produto_path(produto.id),
                    method: :delete,
                    data: { confirm: "Tem certeza que deseja remover o produto #{produto.nome}?" },
                    class:"btn btn-danger" %></td>
        </tr>
        <% end %>
    </tbody>
</table>